Lesson3
TrubnikovSergey/fast-company pull request #1
Opened 2022-07-12 17:30 UTC by TrubnikovSergey

2022-07-12 19:06 UTC, AndreiSachuk requested changes

2022-07-12 19:06 UTC, AndreiSachuk commented on src/app/components/bookmark.jsx
> +    const [bookMark, setBookMark] = useState(status)
почему стейт?
у нас должен быть единый источник истины

2022-07-12 19:06 UTC, AndreiSachuk commented on src/app/components/users.jsx
> +    const table = (
почему это не метод, а константа?
мы его должны вызвать, только когда у нас есть юзеры, а не просчитать, а потом уже думать отображать или нет

2022-07-12 19:06 UTC, AndreiSachuk commented on src/index.js
> +    return <Users/>
А тут не должно быть обертки?
Ты за основу брал проект в уроке?

2022-07-13 10:21 UTC, TrubnikovSergey commented on src/app/components/bookmark.jsx
> +    const [bookMark, setBookMark] = useState(status)
Поправил. Проверь плиз.

2022-07-13 10:21 UTC, TrubnikovSergey commented on src/index.js
> +    return <Users/>
Обертку дописал. Забыл про index.js и app.js.

2022-07-13 10:22 UTC, TrubnikovSergey commented on src/app/components/users.jsx
> +    const table = (
На метод константу исправил. Логику эту не замечал, которую ты описал с методом и константой. Буду теперь помнить.

2022-07-13 14:30 UTC, AndreiSachuk approved these changes
не совсем так, как хотел, но уже прям почти хорошо)
посмотри эталон обзательно)

2022-07-18 15:09 UTC, merged